getwd()
library(tidyverse)
library(dplyr)
library(psych)
library(ggplot2)
setwd("C:/Users/Infinity-OS/Desktop/Project/HR")
hr=read.csv("hr_train.csv",stringsAsFactors = FALSE,header=T)
hr_test=read.csv("hr_test.csv",stringsAsFactors = T,header=T)
hr<-hr%>%mutate(EmployeeLabel = rownames(hr))
table(hr$left)
ggplot(data = hr, aes(x=sales, y=satisfaction_level, color=as.factor(left)))+geom_point()+ggtitle("Satisfaction Level and Job Types")+labs(y="Satisfaction Level", x="Job Types", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=sales, y=satisfaction_level))+geom_boxplot()+ggtitle("Satisfaction Level and Job Types")+labs(y="Satisfaction Level", x="Job Types")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=salary, y=satisfaction_level, color=as.factor(left)))+geom_point()+ggtitle("Satisfaction Level and Income Level")+labs(y="Satisfaction Level", x="Income Level", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=last_evaluation, y=satisfaction_level, color=as.factor(left)))+geom_smooth()+ggtitle("Satisfaction Level and Last Evaluation")+labs(y="Satisfaction Level", x="Last Evaluation", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=number_project, y=satisfaction_level, color=as.factor(left)))+geom_point()+ggtitle("Satisfaction Level and Number of Projects")+labs(y="Satisfaction Level", x="Number of Projects", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=average_montly_hours, y=number_project, color=as.factor(left)))+geom_smooth()+ggtitle("Average Monthly Hours and Number of Projects")+labs(y="Average Monthly Hours", x="Number of Projects", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
ggplot(data = hr, aes(x=last_evaluation, y=number_project, color=as.factor(left)))+geom_point()+ggtitle("Last Evaluation and Number of Projects")+labs(y="Number of Projects", x="Last Evaluation", colour="Left Organization")+theme(plot.title = element_text(hjust = 0.5))
set.seed(123)
inTrain<-createDataPartition(y=hr$left, p=0.75, list = FALSE)  
train<-hr[inTrain,]
test<-hr[-inTrain,]
correlationMatrix <- cor(hr[,1:6])
print(correlationMatrix)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.5)
print(highlyCorrelated)
model <- train(as.factor(left)~.-EmployeeLabel, data=train, method="rpart")
importance <- varImp(model, scale=FALSE)
print(importance)
plot(importance)
control <- rfeControl(functions=rfFuncs, method="cv", number=3)
results <- rfe(train[,1:6], as.factor(train[,7]), sizes=c(1:8), rfeControl=control)
print(results)
predictors(results)
plot(results, type=c("g", "o"))

fitControl<-trainControl(method = "repeatedcv", number = 10, repeats = 3)
fit_3<-train(as.factor(left)~satisfaction_level+number_project+time_spend_company+average_montly_hours+last_evaluation, data = train[,!colnames(train) %in% c("EmployeeLabel")], method = "rpart", parms = list(split = "information"), trControl=fitControl, tuneLength = 10)
predict_3<-predict(fit_3, newdata=hr_test)
write.csv(score,"score.csv")
score=predictrandomForest(predict_3,newdata= hr_test, type="prob")[,1]
score_1=predict(results,newdata=hr_test, type="prob")[,1]
write.csv(score_1,"score_1.csv")
score=predict(predict_3,newdata= hr_test, type="vector")[,1]

usionMatrix(predict_3, test$left)
